# configuration for master
-
  branches:
    only:
    - master

  environment:
    # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    # Disable sending usage data to Microsoft
    DOTNET_CLI_TELEMETRY_OPTOUT: true

  version: 6.8.0.{build}
  image: Visual Studio 2017
  configuration: Release
  install:
  - cmd: 
  nuget:
    disable_publish_on_pr: true
  build_script:
  - cmd: |
      dotnet --info
      msbuild /restore  /p:Configuration=Release /p:version=%APPVEYOR_BUILD_VERSION% -verbosity:minimal DynamicData.sln
      appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\DynamicData\bin\Release\DynamicData.%APPVEYOR_BUILD_VERSION%.nupkg
      appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\DynamicData.ReactiveUI\bin\Release\DynamicData.ReactiveUI.%APPVEYOR_BUILD_VERSION%.nupkg

  test: off
  test_script:
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%
      dotnet test DynamicData.Tests\DynamicData.Tests.csproj --configuration Release --no-build --no-restore
      dotnet test DynamicData.ReactiveUI.Tests\DynamicData.ReactiveUI.Tests.csproj --configuration Release --no-build --no-restore

  deploy:
  - provider: NuGet
    api_key:
      secure: CnOOhO/BwAogsD+dC9Q9BD38q6nxehHPS5LOHU977QtiJpqx3qE6vP+V+GHzpwac
    skip_symbols: false
    on:
      # Only publish from the master branch
      branch: master
      appveyor_repo_tag: true

# configuration for version 4
-
  version: 4.16.0.{build}
  branches:
    only:
    - Version4
  image: Visual Studio 2017
  configuration: Release
  platform: Any CPU
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  nuget:
    account_feed: true
    disable_publish_on_pr: true
  before_build:
  - cmd: |
      appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
      nuget restore DynamicData.sln
  build:
    project: DynamicData.sln
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    verbosity: minimal
  after_build:
  - cmd: |
      7z a DynamicData.zip %APPVEYOR_BUILD_FOLDER%\DynamicData\bin\Release\*.*
      appveyor PushArtifact DynamicData.zip
  test: off
 # test_script:
 # - cmd: >-
 #     cd %APPVEYOR_BUILD_FOLDER%
 #   
 #    %APPVEYOR_BUILD_FOLDER%\packages\xunit.runner.console.2.2.0\tools\xunit.console %APPVEYOR_BUILD_FOLDER%\DynamicData.Tests\bin\Release\DynamicData.Tests.dll
  deploy:
  - provider: NuGet
    api_key:
      secure: CnOOhO/BwAogsD+dC9Q9BD38q6nxehHPS5LOHU977QtiJpqx3qE6vP+V+GHzpwac
    skip_symbols: false
    on:
      # Only publish from the Version4 branch
      branch: Version4
      appveyor_repo_tag: true

# configuration for all other branches
-
  branches:
    except:
    - master
    - Version4

  environment:
    # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    # Disable sending usage data to Microsoft
    DOTNET_CLI_TELEMETRY_OPTOUT: true

  version: 99.99.99.{build}-branches
  image: Visual Studio 2017
  configuration: Release
  install:
  - cmd: 
  nuget:
    disable_publish_on_pr: true
  
  build_script:
  - cmd: |
      dotnet --info
      msbuild /restore  /p:Configuration=Release /p:version=%APPVEYOR_BUILD_VERSION% -verbosity:minimal DynamicData.sln
      appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\DynamicData\bin\Release\DynamicData.%APPVEYOR_BUILD_VERSION%.nupkg
      appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\DynamicData.ReactiveUI\bin\Release\DynamicData.ReactiveUI.%APPVEYOR_BUILD_VERSION%.nupkg

  test: off
  # Hangs indefinitely and I do not know why as the same command works locally
  test_script:
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%
      dotnet test DynamicData.Tests\DynamicData.Tests.csproj --configuration Release --no-build --no-restore
      dotnet test DynamicData.ReactiveUI.Tests\DynamicData.ReactiveUI.Tests.csproj --configuration Release --no-build --no-restore
